"""
Data Pipeline Module for GridLock Zero
Handles loading, caching, and transforming data for the dashboard.
"""
import pandas as pd
import numpy as np
from pathlib import Path

# Automatically finds the project root folder regardless of where this script runs
PROJECT_ROOT = Path(__file__).parent.parent


def load_ccis_data():
    """Load the CCIS scores generated by ALPHA."""
    file_path = PROJECT_ROOT / "data" / "processed" / "ccis_scores.csv"
    if not file_path.exists():
        raise FileNotFoundError(f"CCIS data not found at {file_path}. Ask ALPHA to run ccis_engine.py.")
    return pd.read_csv(file_path)


def load_processed_data():
    """Load the full processed dataset with H3 columns."""
    file_path = PROJECT_ROOT / "data" / "processed" / "processed_data.csv"
    if not file_path.exists():
        raise FileNotFoundError(f"Processed data not found at {file_path}. Ask ALPHA to run h3_indexer.py.")
    return pd.read_csv(file_path)


def get_top_hotspots(df, hour, top_n=5):
    """Filter high-CCIS zones for a specific hour and return the top N."""
    filtered = df[df['hour'] == hour]
    return filtered.sort_values('ccis', ascending=False).head(top_n)


def prepare_map_data(df, hour, resolution=8):
    """Format and group geographic data specifically for Pydeck mapping visualization."""
    h3_col = f'h3_{resolution}'

    # Filter for the selected hour copy
    map_df = df[df['hour'] == hour].copy()
    if map_df.empty:
        return pd.DataFrame(columns=['lat', 'lon', 'ccis', 'fill_color'])

    if h3_col in map_df.columns:
        # Group by the active H3 spatial hexagon resolution
        map_df = map_df.groupby(h3_col).agg({
            'latitude': 'first',
            'longitude': 'first',
            'ccis': 'mean'
        }).reset_index()

    map_df = map_df.rename(columns={'latitude': 'lat', 'longitude': 'lon'})

    # Conditional coloring logic based on threat severity index
    def get_color(ccis):
        if ccis >= 6.0:
            return [255, 50, 50, 200]  # Dynamic semi-transparent Red
        elif ccis >= 3.0:
            return [255, 200, 50, 200]  # Amber
        return [50, 200, 50, 150]  # Green

    map_df['fill_color'] = map_df['ccis'].apply(get_color)
    return map_df.dropna(subset=['lat', 'lon'])